import type { Metadata } from "next";
import { Content, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModel";
import AddPropertyModal from "./components/modals/AddProperyModal";
import SearchModal from "./components/modals/SearchModal";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Django bnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content=  (
    
      <p>Yo yo</p>
    
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>
        
        <div className="pt-32">
          {children}
        </div>

        <LoginModal />
        <SearchModal />
        <SignupModal />
        <AddPropertyModal />

      </body>
    </html>
  );
}
